"""Clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pdcGzKqF7tTAb53cRk2YN8WVuVFxEikH?usp=sharing
"""

import pandas as pd
df =pd.read_csv("student_data.csv")
df=df.sort_values("ID")
def assign_grade(score):
    if score < 60:
        return "F"
    elif 60 <= score < 67:
        return "D"
    elif 67 <= score < 76:
        return "C"
    elif 76 <= score < 89:
        return "B"
    else:
        return "A"
df = df.dropna(subset=[col for col in df.columns if col != 'Score'])
df['Score'].fillna(0, inplace=True)
df.loc[df['Attendance'].str.strip().str.lower() == 'absent', 'Score'] = 0
df = df.drop_duplicates(subset=['ID','Level','Subject'], keep='first')
df['Date'] = pd.to_datetime(df['Date'])
df['Performance_Grade'] = df['Score'].apply(assign_grade)
display(df)
df.to_csv("studentsdataset_cleaned.csv", index=False)

df =pd.read_csv("student_data.csv")
df